---
- name: test
  hosts: server
  become: yes  

  tasks:
   - name: update repo
     apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
   
   - name: Upgrade
     apt: upgrade=dist force_apt_get=yes
     register: log   
 
   - debug:
      var: log.stdout_lines 
